title: "Plan Your Legacy Today: A Singapore Government Initiative"
url: https://www.planyourlegacy.gov.sg
favicon: /images/fav_mylegacy.png
colors:
  primary-color: "#ea9947"
  secondary-color: "#2a4774"
  media-colors:
    - title: media-color-one
      color: "#49759a"
    - title: media-color-two
      color: "#49759a"
    - title: media-color-three
      color: "#00838f"
    - title: media-color-four
      color: "#00838f"
    - title: media-color-five
      color: "#00838f"
description: Sudden death and mental incapacity can happen to any of us. Yet few
  of us plan for these. Don’t leave your loved ones struggling to pick up the
  pieces. Plan your legacy today. A Singapore Government Initiative.
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging-lite.dqfusu0pqovxq.amplifyapp.com
prod: https://master.didl1zpcxc2uu.amplifyapp.com
facebook-pixel: ""
resources_name: resources
shareicon: /images/logo_my_legacyv2.png
is_government: true
google_analytics_ga4: G-T9B2BBXDBB
linkedin-insights: ""
